name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      
    - name: Setup MSBuild Path
      uses: actions/setup-msbuild@v1
           
    - name: Build
      run: msbuild .\CoordainteConversionUtility.sln -t:Rebuild -p:Configuration=Debug
      
    - name: Test
      run: mstest /testcontainer:.\\CoordinateConversionUtility_UnitTests\bin\Debug\CoordinateConversionUtility_UnitTests.dll
