name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.0
           
    - name: Test
      run: dotnet test $env:Test_Project_Path
      
